- buildSrc/src/main/groovy/org.alvearie.imaging.ingestion.common-conventions.gradle
- imaging-ingestion-operator/Makefile
- imaging-ingestion-operator/common/constants.go
- imaging-ingestion-operator/config/manager/kustomization.yaml
- imaging-ingestion-operator/deploy/manifests.yaml
> Set initial version to be 0.0.1

- .github/workflows/main.yaml
- build.gradle
- dicom-event-driven-ingestion/src/test/resources/application.properties
> Add github action

- dicomweb-stow-service/build.gradle
> Remove unused dependency

- .github/workflows/main.yaml
> Build optimized native images on Merge

- .github/workflows/main.yaml
- dicom-event-driven-ingestion/build.gradle
- dicom-event-driven-ingestion/src/main/resources/application.properties
- imaging-ingestion-operator/common/constants.go
> Build postgresql and db2 backed Event Driven Ingestion Images

- imaging-ingestion-operator/Makefile
- imaging-ingestion-operator/common/constants.go
- imaging-ingestion-operator/deploy/manifests.yaml
- imaging-ingestion-operator/main.go
> Keep operator running and auto detect dependency

- dicom-search-model/src/main/java/org/alvearie/imaging/ingestion/model/result/DicomAttribute.java
- dicom-search-model/src/main/java/org/alvearie/imaging/ingestion/model/result/DicomQueryModel.java
> Register for Reflection

- dicomweb-wado-service/build.gradle
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
> Add metadata endpoint to WADO

- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
> Fix MediaType for metadata

- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/EventProcessorFunction.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
> Add frames/frameList endpoint in WADO

- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/QidoResource.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/RenderService.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
- dicomweb-wado-service/src/main/resources/application.properties
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/QidoResourceTest.java
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/WadoResourceTest.java
- dicomweb-wado-service/src/test/resources/application.properties
> Enable gzip compression

- dicom-event-driven-ingestion/build.gradle
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/QueryHelper.java
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/QueryResource.java
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/RetrieveService.java
- dicom-event-driven-ingestion/src/test/java/org/alvearie/imaging/ingestion/QueryResourceTest.java
- dicom-event-driven-ingestion/src/test/resources/application.properties
- dicom-persistence-model/src/main/java/org/alvearie/imaging/ingestion/entity/DicomInstanceEntity.java
- dicom-persistence-model/src/main/java/org/alvearie/imaging/ingestion/entity/DicomSeriesEntity.java
- dicom-persistence-model/src/main/java/org/alvearie/imaging/ingestion/entity/DicomStudyEntity.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/DicomQueryClient.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/QidoResource.java
- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
- dicomweb-wado-service/src/main/resources/application.properties
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/QidoResourceTest.java
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/WadoResourceTest.java
- imaging-ingestion-operator/bundle/manifests/imaging-ingestion-operator.clusterserviceversion.yaml
- imaging-ingestion-operator/config/manager/manager.yaml
- imaging-ingestion-operator/deploy/manifests.yaml
- imaging-ingestion-operator/model/wado_service.go
> Filter by source

- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/WadoResourceTest.java
> Fix missing source filter

- imaging-ingestion-operator/controllers/dicomwebingestionservice/dicomwebingestionservice_reconciler.go
- imaging-ingestion-operator/model/wado_service.go
> Update WADO KService Env on CR change

- dicomweb-stow-service/src/main/resources/application.properties
> Make Max Body Size configurable

- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/EventProcessorFunction.java
- dicom-event-driven-ingestion/src/test/java/org/alvearie/imaging/ingestion/EventProcessorFunctionTest.java
> Fix instance url of DicomAvailableEvent

- dicomweb-fhir-binding/main.go
- dicomweb-fhir-binding/model/fhir/imaging_study.go
- dicomweb-fhir-binding/test/fhir.json
> Remove dangled endpoint reference at study level

- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/WadoResourceTest.java
> Fix BulkDataURI for metadata endpoint

- dicomweb-wado-service/src/main/java/org/alvearie/imaging/ingestion/service/wado/WadoResource.java
- dicomweb-wado-service/src/test/java/org/alvearie/imaging/ingestion/service/wado/WadoResourceTest.java
> Support XML Metadata endpoint

- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/Constants.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/nats/NatsAssociationSubscriber.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/DimseRQProxyHandler.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/Main.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/NatsAssociationPublisher.java
- dicom-dimse-proxy/src/main/resources/application.properties
- dicom-dimse-proxy/src/test/resources/application.properties
- dicom-dimse-service/src/test/resources/application.properties
Run proxy server in onprem and cloud modes so that bi-directional communication can happen
> Run proxy server always

- .github/workflows/main.yaml
> Publish binary artifacts

- .github/workflows/main.yaml
- dicom-dimse-proxy/src/test/resources/dicom-dimse-proxy.sh
> Include a script template in tar to run DIMSE proxy from command line

- dicomweb-common-service/src/main/java/org/alvearie/imaging/ingestion/service/s3/SimpleStoreService.java
> Include file meta information when storing dicom

- dicom-search-model/build.gradle
- dicomweb-common-service/build.gradle
> Skip quarkusBuild task for library projects

- imaging-ingestion-operator/common/readiness_checks.go
- imaging-ingestion-operator/controllers/dicomeventdriveningestion_controller.go
- imaging-ingestion-operator/controllers/dicomeventdriveningestion_reconciler.go
- imaging-ingestion-operator/controllers/dicomeventdriveningestion_state.go
- imaging-ingestion-operator/controllers/dicominstancebinding_controller.go
- imaging-ingestion-operator/controllers/dicominstancebinding_reconciler.go
- imaging-ingestion-operator/controllers/dicominstancebinding_state.go
- imaging-ingestion-operator/controllers/dicomstudybinding_controller.go
- imaging-ingestion-operator/controllers/dicomstudybinding_reconciler.go
- imaging-ingestion-operator/controllers/dicomstudybinding_state.go
- imaging-ingestion-operator/controllers/dicomwebingestionservice_controller.go
- imaging-ingestion-operator/controllers/dicomwebingestionservice_reconciler.go
- imaging-ingestion-operator/controllers/dicomwebingestionservice_state.go
- imaging-ingestion-operator/controllers/dimseingestionservice_controller.go
- imaging-ingestion-operator/controllers/dimseingestionservice_reconciler.go
- imaging-ingestion-operator/controllers/dimseingestionservice_state.go
- imaging-ingestion-operator/controllers/dimseproxy_controller.go
- imaging-ingestion-operator/controllers/dimseproxy_reconciler.go
- imaging-ingestion-operator/controllers/dimseproxy_state.go
- imaging-ingestion-operator/controllers/suite_test.go
- imaging-ingestion-operator/main.go
> Refactoring controllers to use common code

- imaging-ingestion-operator/api/v1alpha1/dicomeventbridge_types.go
- imaging-ingestion-operator/bundle/manifests/imaging-ingestion-operator.clusterserviceversion.yaml
- imaging-ingestion-operator/bundle/manifests/imaging-ingestion.alvearie.org_dicomeventbridges.yaml
- imaging-ingestion-operator/common/constants.go
- imaging-ingestion-operator/config/crd/bases/imaging-ingestion.alvearie.org_dicomeventbridges.yaml
- imaging-ingestion-operator/config/manifests/bases/imaging-ingestion-operator.clusterserviceversion.yaml
- imaging-ingestion-operator/controllers/dicomeventbridge_controller_test.go
- imaging-ingestion-operator/controllers/dicomeventbridge_reconciler.go
- imaging-ingestion-operator/controllers/dicomeventbridge_state.go
- imaging-ingestion-operator/deploy/manifests.yaml
- imaging-ingestion-operator/model/eventbridge_deployment.go
> Configure mailbox when running in edge role

- dicom-dimse-service/src/main/resources/application.properties
- dicom-dimse-service/src/main/resources/serialization-config.json
> Add serialization config for dimse ingestion service

- imaging-ingestion-operator/controllers/common.go
- imaging-ingestion-operator/controllers/dimseingestionservice_reconciler.go
- imaging-ingestion-operator/controllers/dimseingestionservice_state.go
- imaging-ingestion-operator/model/dimseingestion_deployment.go
> Add missing env vars to dimse ingestion service

- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/CEchoHandler.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/CStoreHandler.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/DimseRQProxyHandler.java
> Add more DIMSE logging and better response handling

- cloud-events/src/main/java/org/alvearie/imaging/ingestion/event/Events.java
- dicom-dimse-service/src/main/resources/application.properties
- dicom-dimse-service/src/test/resources/application.properties
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/EventProcessorFunction.java
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/StudyManager.java
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/StudyRevisionEventClient.java
- dicom-event-driven-ingestion/src/main/resources/application.properties
- dicom-event-driven-ingestion/src/test/java/org/alvearie/imaging/ingestion/EventProcessorFunctionTest.java
- dicom-event-driven-ingestion/src/test/resources/application.properties
- dicomweb-common-service/src/main/java/org/alvearie/imaging/ingestion/service/client/StudyStoredEventClient.java
- dicomweb-common-service/src/main/java/org/alvearie/imaging/ingestion/service/s3/SimpleStoreService.java
- dicomweb-common-service/src/test/java/org/alvearie/imaging/ingestion/service/s3/SimpleStoreServiceTest.java
- dicomweb-common-service/src/test/resources/application.properties
- dicomweb-stow-service/src/main/resources/application.properties
- dicomweb-stow-service/src/test/resources/application.properties
- dicomweb-wado-service/src/main/resources/application.properties
- dicomweb-wado-service/src/test/resources/application.properties
- imaging-ingestion-operator/model/dimseingestion_deployment.go
- imaging-ingestion-operator/model/eventprocessor_service.go
- imaging-ingestion-operator/model/stow_service.go
> Add Event Source

- imaging-ingestion-operator/Makefile
- imaging-ingestion-operator/README.md
- imaging-ingestion-operator/bundle.Dockerfile
- imaging-ingestion-operator/bundle/manifests/imaging-ingestion-operator.clusterserviceversion.yaml
- imaging-ingestion-operator/bundle/metadata/annotations.yaml
- imaging-ingestion-operator/config/manager/kustomization.yaml
- imaging-ingestion-operator/config/manifests/bases/imaging-ingestion-operator.clusterserviceversion.yaml
- imaging-ingestion-operator/deploy/manifests.yaml
> Operator v0.0.3

- .github/workflows/main.yaml
- dicom-dimse-service/build.gradle
- dicomweb-common-service/build.gradle
- dicomweb-stow-service/build.gradle
- dicomweb-wado-service/build.gradle
- gradle.properties
> Fix native build

- dicom-dimse-service/build.gradle
- dicom-event-driven-ingestion/build.gradle
- dicomweb-common-service/build.gradle
- dicomweb-stow-service/build.gradle
- dicomweb-wado-service/build.gradle
- dicomweb-wado-service/src/main/resources/application.properties
> Exclude apache commons-logging dependency

- dicom-dimse-service/build.gradle
- dicom-event-driven-ingestion/build.gradle
- dicomweb-common-service/build.gradle
- dicomweb-stow-service/build.gradle
- dicomweb-wado-service/build.gradle
> Exclude commons-logging globally

- .github/workflows/main.yaml
> Use quarkus 2.4.2.Final for dimse service and proxy

- .github/workflows/main.yaml
> Use jvm mode for dimse service temporarily

- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/nats/NatsAssociationSubscriber.java
- dicom-dimse-service/src/test/resources/bucket/LOCAL_STORAGE_PATH
- dicomweb-common-service/src/main/java/org/alvearie/imaging/ingestion/service/s3/LocalFileService.java
- dicomweb-common-service/src/main/java/org/alvearie/imaging/ingestion/service/s3/StoreConfiguration.java
> Improve concurrency for association

- imaging-ingestion-operator/controllers/common.go
- imaging-ingestion-operator/controllers/dimseingestionservice_reconciler.go
- imaging-ingestion-operator/controllers/dimseingestionservice_state.go
> Filter web ingestion lookup in DIMSE service by provider

- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/CEchoHandler.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/CStoreHandler.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/DimseCommandHandler.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/dimse/DimseCommandRegistry.java
- dicom-dimse-common/src/main/java/org/alvearie/imaging/ingestion/service/nats/NatsMessageSubscriber.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/DimseRQProxyHandler.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/NatsMessagePublisher.java
> Release target association on finish

- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/DimseRQProxyHandler.java
- dicom-dimse-proxy/src/main/java/org/alvearie/imaging/ingestion/dimse/proxy/NatsMessagePublisher.java
> Fix association release

- dicom-cstore-binding/src/main/docker/Dockerfile.native
- dicom-dimse-proxy/src/main/docker/Dockerfile.native
- dicom-dimse-service/src/main/docker/Dockerfile.native
- dicom-event-driven-ingestion/src/main/docker/Dockerfile.native
- dicomweb-stow-service/src/main/docker/Dockerfile.native
https://www.graalvm.org/22.0/reference-manual/native-image/MemoryManagement/
> Add heap settings for native image

- docs/dicom-instance-binding/overview.md
Signed-off-by: Richard Duggan <rduggan@ca.ibm.com>
> Update instance binding docs for C-STORE

- cloud-events/src/main/java/org/alvearie/imaging/ingestion/event/DicomStudy.java
- dicom-event-driven-ingestion/src/main/java/org/alvearie/imaging/ingestion/StudyRevisonEventBuilder.java
- Adding study date field to DicomStudy
> Adding StudyDate to DicomStudy and StudyRevisionEvent
